#1 task

In [20]:
import numpy as np
import pandas as pd

In [39]:
df=pd.read_csv('data.csv')
df.head()

job_title      hh_title   age    salary  exp_period  \
0  data analyst  Data analyst  22.0       NaN        2.67   
1  data analyst  Data Analyst  21.0       NaN        0.83   
2  data analyst  Data Analyst  30.0       NaN        7.50   
3  data analyst  Data Analyst  24.0       NaN        4.92   
4  data analyst  Data Analyst  27.0  450000.0        3.25   

                    title_of_exp  
0                   Data Analyst  
1            Junior Data Analyst  
2                   Data Analyst  
3                   Data Analyst  
4  Business Intelligence Analyst

#2 task

In [62]:
df_data=df.loc[:,['job_title','age','salary','exp_period']]
df_data=df_data.dropna()
print(df_data)

        job_title   age     salary  exp_period
4    data analyst  27.0   450000.0        3.25
11   data analyst  25.0   860000.0        2.92
12   data analyst  28.0   950000.0        7.25
15   data analyst  29.0   500000.0        6.75
21   data analyst  22.0   500000.0        3.33
..            ...   ...        ...         ...
989           sql  56.0      860.0       15.25
990           sql  32.0   645000.0       10.67
991           sql  28.0   200000.0        6.58
992           sql  38.0   500000.0       11.42
994           sql  29.0  1505000.0        0.58

[274 rows x 4 columns]


#3 and #4 task

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
x=df_data.drop('job_title',axis=1).values
y=df_data['job_title']

#5 task

In [64]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,stratify=y)

In [65]:
xtrain

array([[2.800e+01, 9.500e+05, 7.250e+00],
       [2.900e+01, 1.500e+05, 0.000e+00],
       [2.500e+01, 8.600e+05, 2.920e+00],
       [2.900e+01, 1.505e+06, 5.800e-01],
       [2.700e+01, 4.500e+05, 3.250e+00],
       [2.700e+01, 4.500e+05, 3.250e+00],
       [2.500e+01, 8.600e+05, 2.920e+00],
       [2.200e+01, 3.000e+05, 1.580e+00],
       [2.800e+01, 5.000e+05, 4.330e+00],
       [2.200e+01, 1.500e+05, 0.000e+00],
       [2.300e+01, 5.500e+05, 2.920e+00],
       [2.800e+01, 1.000e+06, 7.420e+00],
       [2.200e+01, 2.000e+05, 8.300e-01],
       [2.100e+01, 5.000e+05, 1.580e+00],
       [3.800e+01, 1.200e+06, 1.733e+01],
       [2.900e+01, 1.505e+06, 5.800e-01],
       [2.800e+01, 2.000e+05, 6.580e+00],
       [3.000e+01, 1.000e+06, 6.670e+00],
       [2.900e+01, 1.505e+06, 5.800e-01],
       [2.200e+01, 5.000e+05, 1.920e+00],
       [2.100e+01, 1.200e+06, 2.330e+00],
       [5.600e+01, 8.600e+02, 1.525e+01],
       [2.400e+01, 3.000e+05, 7.500e-01],
       [2.800e+01, 9.500e+05, 7.25

In [66]:
ytrain

92     data analyst
629          python
131    data analyst
834             sql
44     data analyst
           ...     
759          python
757          python
857             sql
644          python
941             sql
Name: job_title, Length: 219, dtype: object

#6 and #7 task

In [67]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [68]:
model.fit(xtrain,ytrain)

GaussianNB()

In [69]:
y_model=model.predict(xtest)

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,y_model)

0.45454545454545453

#8 task

In [71]:
from sklearn.model_selection import cross_val_score

In [72]:
info=cross_val_score(model,x,y,cv=10)
info

array([0.5       , 0.46428571, 0.46428571, 0.5       , 0.44444444,
       0.48148148, 0.44444444, 0.48148148, 0.44444444, 0.48148148])

In [73]:
info.mean()

0.47063492063492063

#9 and #10 task

In [74]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3)

In [75]:
model.fit(x,y)
y_model=model.predict(x)

In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_model)

0.9452554744525548

#11 task

In [77]:
from sklearn.model_selection import LeaveOneOut

In [78]:
scores=cross_val_score(model,x,y,cv=LeaveOneOut())
scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [79]:
scores.mean()

0.9452554744525548